### ISSUE TITLE
Rename manages to memberAssertion

### ISSUE THREAD

**Issue by asbjornu** [HydraCG/Specifications#150]
Can we please rename the `manages` property wrt. collections to `contains`? I just find the latter to be so much more self-descriptive than the former.

**Comment by tpluscode** [comment]
For reference here's some prior discussion on this subject: https://www.w3.org/community/hydra/wiki/Collection_Design

Especially down at the bottom is a list of suggested names

**Comment by elf-pavlik** [comment]
I think we should name it in a way that relates to Triple Pattern Fragment work, I opened #142 as a broader issue for how `manages` block and TPF do fit together.

Since we discuss `hydra:memberTemplate` in #16 IMO we should stay away from *template* for current `manages` block. How about `memberPattern` since we use *triple patterns*?

**Comment by alien-mcl** [comment]
It seems that the 'manages' term is somehow unacceptable and there are other ideas of renaming it - I'm reopening it

**Comment by asbjornu** [comment]
As [discussed on Slack](https://httpapis.slack.com/archives/CF928CBAM/p1559125770010300), `memberAssertion` better describes what this property means. If it hadn't been for the collision with `rdf:predicate`, that would have been the perfect name for this property imho, but alas.

**Comment by alien-mcl** [comment]
PR #219 covers this issue - closing
