### ISSUE TITLE
hydra:PagedCollection - Mentioned in image but not in spec

### ISSUE THREAD

**Issue by pietercolpaert** [HydraCG/Specifications#169]
Does the term hydra:PagedCollection exist at all? Or is it only an example given in the illustration of an implementation of a hydra:Collection?

**Comment by alien-mcl** [comment]
Hi @pietercolpaert 

The `hydra:PagedCollection` is no more in favour of `hydra:PartialCollectionView` and few other constructs since resolution of #42 and commit 225aa5117.
Indeed, the image is obsolete and needs to be updated.

You can take a quick look on [use cases](/HydraCG/Specifications/tree/master/drafts/use-cases) and [Heracles.ts](/HydraCG/Heracles.ts) for reference. You'll find some examples and tests that should be quite up to date with the spec (except of `hydra:memberTemplate' which didn't make to the spec so far).

**Comment by pietercolpaert** [comment]
Ok, thanks! I hope the image can be updated soon!
