### ISSUE TITLE
Rethink paging

### ISSUE THREAD

**Issue by RubenVerborgh** [HydraCG/Specifications#42]
As [discussed on the mailing list](http://lists.w3.org/Archives/Public/public-hydra/2014Apr/0034.html), the current implementation of paging might be confusing. This became apparent when I was implementing this for [the Linked Data Fragments server](http://data.linkeddatafragments.org/dbpedia) (try the Turtle or JSON-LD representaiton).

Basically, the whole misconception for me comes with the term `PagedCollection`. If I told you "x is a paged collection", what would you expect? That x is a single page or that x is a collection that is accessible as pages?
Hydra says that a `PagedCollection` is  a page, as is apparent from the current spec:

```javascript
// EXAMPLE 14: A Hydra PagedCollection splits a collection into multiple pages
{
  "@context": "http://www.w3.org/ns/hydra/context.jsonld",
  "@id": "http://api.example.com/an-issue/comments?page=3",
  "@type": "PagedCollection",
  "totalItems": "4980",
  "itemsPerPage": "10",
  "firstPage": "/an-issue/comments?page=1",
  "nextPage": "/an-issue/comments?page=4",
  "previousPage": "/an-issue/comments?page=2",
  "lastPage": "/an-issue/comments?page=498",
  "member": [

  ]
}
```

This seems like a misnomer. What can we do to fix? Suggestions in comments.

---
BTW @lanthaler I would be totally willing to write this into the spec.

**Comment by lanthaler** [comment]
Proposals are being tracked at https://www.w3.org/community/hydra/wiki/Pagination

**Comment by lanthaler** [comment]
PROPOSAL: Look at pages of a collection as specific *views* on a single underlying collection instead of thinking of the collection as the sum of its pages. More concretely,
 - replace PagedCollection with PartialCollectionView,
 - replace firstPage/nextPage/previousPage/lastPage with first/next/previous/last,
 - associate totalItems with Collection instead of PagedCollection, and
 - remove itemsPerPage for the time being (we will likely re-introduce it with a different name).

**Comment by lanthaler** [comment]
Call for consensus: https://lists.w3.org/Archives/Public/public-hydra/2015Oct/0163.html

**Comment by lanthaler** [comment]
RESOLVED: Change the current pagination design by replacing `PagedCollection` with `PartialCollectionView`, replacing `firstPage`/`nextPage`/`previousPage`/`lastPage` with `first`/`next`/`previous`/`last`, associating `totalItems` with `Collection` instead of `PagedCollection`, and removing `itemsPerPage`.

**Comment by tpluscode** [comment]
I've just noticed that [the wiki page](https://www.w3.org/community/hydra/wiki/Pagination) is outdated. Should it be deleted?

**Comment by akuckartz** [comment]
@tpluscode It does not seem to be optimal to use a comment in this closed issue for that question.

**Comment by lanthaler** [comment]
It isn't outdated (This page collects design proposals for ISSUE-42 - it still does). We should keep stuff around to document what we did.

**Comment by tpluscode** [comment]
Fair enough. But the page doesn't say that the issue has been closed. One could get the impression that the design still hasn't been decided on

**Comment by nicksloan** [comment]
I just wanted to mention that today I found that wiki page and wondered myself if the discussion had been resolved or not. Glad to see it has, as I think that PartialCollectionView is a great way to handle this, but I do think the wiki should be updated to indicate resolution. Adding a note to the top of the document would preserve the discussion, but also help to avoid confusing people new to Hydra.
